### ISSUE TITLE
Translation failing to return the complete batch

### ISSUE THREAD

**Issue by jbajou** [maltekuhr/laravel-gpt#4]
Hi,

This package looks interesting and I wanted to give it a swirl. My playground is to create a command to translate my en.json to another language, Italian let's say 🍕.

# context
Here is what I do:
- I open the json file and load it into an array
- I chunk the array by 20 lines
- I send this to a `GPTAction` after having imploded the array with `\n`

My GPTAction usage looks like this (I call it foreach chunk):
```
TranslateGPTAction::make('Italian')->send(implode("\n", $keys))['translation']
```
The parameter sent to the `send()` method looks like:
```
foo\nbar\nbaz
```

# Problem
The first loop, i get the proper amount of lines translated (i.e 20). For the second loop, I always get only one line.
After diving a bit in the plugin, I see that Chat GPT is only returning the first line on the second loop. I tried to wait a bit between iterations, but no impact.

Anyone has an idea ?

Thanks in advance

**Comment by maltekuhr** [comment]
Hi @jbajou,

Thank you for reaching out and providing details about the issue you're encountering. To ensure I've understood correctly, you're attempting to translate JSON strings from English to Italian, chunking the JSON array into batches of 20 lines, and using a `TranslateGPTAction`. The first batch translates correctly, but subsequent batches only return one line of translation.

Based on the information provided, it's challenging to pinpoint the exact cause without more context. Here are a few suggestions that could help us diagnose and potentially solve the issue:

1. **Environment Details**: Can you share the versions of PHP, Laravel, and any relevant packages you're using? This information can be crucial in reproducing the issue.

2. **Error Logs**: Are there any error messages or logs that occur when the translation fails? Exact messages can offer significant clues.

3. **Code Snippets**: While you've shared your approach, a minimal reproducible example of the code triggering the issue would be invaluable. This includes how you're calling `TranslateGPTAction` in the loop and any modifications you've tried.

4. **Detailed Description**: More details on how `TranslateGPTAction` is expected to work in this scenario and any specific configurations you've set could also be helpful.

5. **Minimal Reproducible Example**: If possible, creating a minimal, publicly shareable version of your code that still exhibits the problem (e.g., a GitHub gist) would greatly aid in diagnosing the issue.

I hope these steps help in narrowing down the cause of the issue. If you manage to gather more information or create a minimal reproducible example, please share it. This will greatly enhance our ability to provide targeted assistance.

I've replicated your setup by creating a TranslateGPTAction to understand the issue you're experiencing. My implementation operates correctly, which suggests that the error might stem from a specific aspect of your setup or potentially a bug in the package. I encourage you to compare your approach with mine to identify any differences that could point to the root cause of the problem. Should you discover a discrepancy that sheds light on what went wrong or if you suspect a bug in the package, please share your findings with me. This will allow me to address the issue promptly, either by correcting the bug or by enhancing our documentation for clearer guidance. Your feedback is invaluable for improving the tool for all users.

**TranslateGPTAction**
```php
<?php

namespace App\GPT\Actions\Test;

use Illuminate\Support\Arr;
use MalteKuhr\LaravelGPT\GPTAction;
use Closure;

class TranslateGPTAction extends GPTAction
{
    public function __construct(
        protected string $language = 'German'
    ) {}

    public function systemMessage(): ?string
    {
        return "Please translate the given translations into {$this->language}. Your input will be translation keys and translated values for an other language. Your forbidden to return translated values in an other language than {$this->language}.";
    }

    public function function(): Closure
    {
        return function (array $translations): array {
            return Arr::mapWithKeys($translations, function ($value) {
                return [$value['key'] => $value['translated']];
            });
        };
    }

    public function rules(): array
    {
        return [
            'translations' => 'required|array|min:1',
            'translations.*.key' => 'required|string',
            'translations.*.translated' => 'required|string',
        ];
    }

    public function temperature(): ?float
    {
        return 0.5;
    }
}
``` 

**TranslateCommand**
```php
<?php

namespace App\Console\Commands;

use App\GPT\Actions\Test\TranslateGPTAction;
use Illuminate\Console\Command;

class TranslateCommand extends Command
{
    protected $signature = 'translate';


    protected $description = 'Translate the given translations into German. Your input will be translation keys and translated values for an other language. Your translated values should be only in German.';

    public function handle(): void
    {
        $chunks = collect(json_decode(file_get_contents(base_path('test.json')), true))->chunk(2);
        $translated = [];

        foreach ($chunks as $chunk) {
            $message = "Spanish Translations: \n" . json_encode($chunk->map(fn($value, $key) => [
                'key' => $key,
                'translated' => $value
            ])->toArray());

            $response = TranslateGPTAction::make()->send($message);

            $translated = [
                ...$translated,
                ...$response
            ];
        }

        dd($translated);
    }
}
```

**Input**
```json
{
    "hello": "hola",
    "good morning": "buenos días",
    "good afternoon": "buenas tardes",
    "good evening": "buenas noches",
    "thank you": "gracias",
    "please": "por favor",
    "yes": "sí",
    "no": "no",
    "goodbye": "adiós",
    "excuse me": "perdón",
    "I love you": "te quiero",
    "how are you?": "¿cómo estás?",
    "what's your name?": "¿cuál es tu nombre?",
    "I don't understand": "no entiendo",
    "help": "ayuda",
    "welcome": "bienvenido",
    "please wait": "por favor espera",
    "sorry": "lo siento"
}
```

**Output**
<img width="422" alt="Screenshot 2024-02-06 at 19 49 10" src="https://github.com/maltekuhr/laravel-gpt/assets/80050109/d5aa8e1b-f2a9-446b-ad1f-ac1eca1be678">
